name: flutter_hls_parser
description: dart plugin for parse m3u8 file for HLS. both of master and media file is supported.
version: 1.0.0
homepage: https://github.com/HiroyukTamura/flutter_hls_parser

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  quiver: ^3.0.0

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
