name: FlutterTest

# This workflow is triggered on pushes to the repository.

on:
  pull_request:

jobs:
  flutter_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: subosito/flutter-action@v2.6.1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test --coverage --coverage-path=~/coverage/lcov.info
      - uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ~/coverage/lcov.info
